app = 'fp-standalone'
primary_region = 'yyz'

[deploy]
  strategy = "immediate"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5173"
  NODE_ENV = "production"

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[checks]
  [checks.health]
    type = 'http'
    port = 5173
    path = '/api/health'
    interval = '30s'
    timeout = '10s'
    grace_period = '120s'

