// server/planning/reports/comprehensive.ts
import type { ComprehensiveReportInputs, RetirementProjection, TaxProjection, RrspAnalysis, TfsaAnalysis, CapitalGainsAnalysis, IncomeSplittingAnalysis, InsuranceAnalysis, EducationAnalysis, EstateAnalysis, DebtAnalysis } from "../types";
import { REPORT_CSS } from "./styles";
import { coverPage, pageHeader, pageFooter, sectionHeader, metricGrid, dataTable, recommendationList, callout, progressBar, twoCol, divider, badge, barChart, lineChart, donutChart, fmt } from "./components";
import { PROVINCE_NAMES } from "../data/taxData2024";

function retirementSection(inputs: ComprehensiveReportInputs, r: RetirementProjection): string {
  const ri = inputs.retirement!;
  const income = [{label:"CPP",value:r.incomeFromCpp},{label:"OAS",value:r.incomeFromOas},{label:"Pension",value:r.incomeFromPension},{label:"RRSP/RRIF",value:r.incomeFromRrsp},{label:"TFSA",value:r.incomeFromTfsa}].filter(d=>d.value>0);
  const sc = r.successProbability>=90?"green":r.successProbability>=75?"blue":r.successProbability>=60?"amber":"red";
  const rows = r.yearByYear.filter((_,i)=>i%5===0).slice(0,14).map(row=>[fmt.age(row.age),fmt.year(row.year),fmt.dollar(row.rrspBalance),fmt.dollar(row.tfsaBalance),fmt.dollar(row.nonRegBalance),fmt.dollar(row.totalBalance),row.withdrawalAmount>0?fmt.dollar(row.withdrawalAmount):"—",fmt.dollar(row.totalIncome)]);
  const ld = r.yearByYear.filter((_,i)=>i%2===0);
  return `<div class="page">${pageHeader(inputs.meta,"Retirement Planning")}${sectionHeader("Section 1","Retirement Planning",`Projection to age ${ri.planToAge} \u2014 ${PROVINCE_NAMES[ri.province]}`)}
  ${metricGrid([{label:"Retirement Age",value:`Age ${ri.retirementAge}`,sub:`${r.yearsToRetirement} years away`},{label:"Savings at Retirement",value:fmt.dollar(r.retirementSavingsAtRetirement),variant:"navy"},{label:"Income Goal",value:fmt.dollar(ri.desiredRetirementIncome)+"/yr",sub:"Today's dollars"},{label:"Success Probability",value:`${r.successProbability}%`,variant:sc,sub:r.portfolioDepletionAge?`<span class="text-red">Depletes at age ${r.portfolioDepletionAge}</span>`:`<span class="text-green">Survives to age ${ri.planToAge}</span>`}])}
  <div class="two-col mb-20"><div>
  ${metricGrid([{label:"RRSP at Retirement",value:fmt.dollar(r.rrspAtRetirement),variant:"blue"},{label:"TFSA at Retirement",value:fmt.dollar(r.tfsaAtRetirement),variant:"blue"},{label:"Non-Reg at Retirement",value:fmt.dollar(r.nonRegAtRetirement),variant:"blue"}],3)}
  ${metricGrid([{label:"CPP Benefit",value:fmt.dollar(r.cppMonthlyBenefit)+"/mo",sub:`Starting age ${ri.cppStartAge}`},{label:"OAS Benefit",value:fmt.dollar(r.oasMonthlyBenefit)+"/mo",sub:`Starting age ${ri.oasStartAge}`},{label:"DB Pension",value:fmt.dollar(ri.pensionMonthly)+"/mo",sub:"Defined benefit"}],3)}
  </div><div>${donutChart("Retirement Income Sources",income)}</div></div>
  ${lineChart("Portfolio Balance Over Time",[{label:"RRSP/RRIF",data:ld.map(row=>({x:row.age,y:row.rrspBalance})),color:"#1E5FA8"},{label:"TFSA",data:ld.map(row=>({x:row.age,y:row.tfsaBalance})),color:"#C9A84C"},{label:"Non-Reg",data:ld.map(row=>({x:row.age,y:row.nonRegBalance})),color:"#1A7A4A"}])}
  ${callout(`<strong>CPP Timing:</strong> Starting CPP at age ${ri.cppStartAge} gives ${fmt.dollar(r.cppMonthlyBenefit)}/month. Break-even vs. starting at 65 is approximately age ${r.cppBreakevenAge}. &nbsp;<strong>OAS Timing:</strong> Break-even vs. starting at 65 is approximately age ${r.oasBreakevenAge}.`,"info")}
  ${callout(`<strong>RRSP vs. TFSA Strategy:</strong> ${r.rrspVsTfsaRationale}`,r.rrspVsTfsaRecommendation==="rrsp"?"info":r.rrspVsTfsaRecommendation==="tfsa"?"success":"info")}
  ${dataTable("Year-by-Year Projection (Every 5 Years)",[{label:"Age"},{label:"Year"},{label:"RRSP/RRIF",right:true},{label:"TFSA",right:true},{label:"Non-Reg",right:true},{label:"Total Portfolio",right:true},{label:"Withdrawal",right:true},{label:"Gross Income",right:true}],rows)}
  ${r.shortfallOrSurplus<0?callout(`<strong>Action Required:</strong> Projected annual retirement income shortfall of ${fmt.dollar(Math.abs(r.shortfallOrSurplus))}. Consider increasing annual savings or adjusting the retirement age.`,"warning"):callout(`<strong>On Track:</strong> Current savings trajectory projects a surplus of ${fmt.dollar(r.shortfallOrSurplus)} annually in retirement.`,"success")}
  ${pageFooter(1,10,inputs.meta.advisor.companyName)}</div>`;
}

function taxSection(inputs: ComprehensiveReportInputs, r: TaxProjection): string {
  return `<div class="page">${pageHeader(inputs.meta,"Tax Planning")}${sectionHeader("Section 2","Tax Projection",`${inputs.tax?.taxYear??new Date().getFullYear()} Tax Year \u2014 ${PROVINCE_NAMES[inputs.tax?.province??inputs.meta.client.province]}`)}
  ${metricGrid([{label:"Gross Income",value:fmt.dollar(r.grossIncome)},{label:"Taxable Income",value:fmt.dollar(r.taxableIncome)},{label:"Total Tax",value:fmt.dollar(r.totalTax),variant:"red"},{label:"After-Tax Income",value:fmt.dollar(r.afterTaxIncome),variant:"green"}])}
  ${metricGrid([{label:"Effective Rate",value:fmt.pct(r.effectiveRate),sub:"Total tax / gross income"},{label:"Marginal Rate",value:fmt.pct(r.marginalRate),variant:"amber",sub:"Federal + provincial"},{label:"Federal Tax",value:fmt.dollar(r.federalTax)},{label:"Provincial Tax",value:fmt.dollar(r.provincialTax)}])}
  ${barChart("Tax Breakdown",[{label:"Federal Tax",value:r.federalTax},{label:"Provincial Tax",value:r.provincialTax},{label:"CPP",value:r.cpp},{label:"EI",value:r.ei}])}
  ${dataTable("Federal Tax Bracket Breakdown",[{label:"Bracket"},{label:"Rate",right:true},{label:"Income in Bracket",right:true},{label:"Tax in Bracket",right:true},{label:"Cumulative Tax",right:true}],r.bracketBreakdown.map(b=>[b.bracket,fmt.pct(b.rate),fmt.dollar(b.incomeInBracket),fmt.dollar(b.taxInBracket),fmt.dollar(b.cumulative)]))}
  ${dataTable("5-Year Tax Projection (2% Annual Income Growth)",[{label:"Year"},{label:"Projected Income",right:true},{label:"Projected Tax",right:true},{label:"Effective Rate",right:true},{label:"Marginal Rate",right:true}],r.fiveYearProjection.map(row=>[row.year.toString(),fmt.dollar(row.projectedIncome),fmt.dollar(row.projectedTax),fmt.pct(row.effectiveRate),fmt.pct(row.marginalRate)]))}
  ${r.recommendations.length>0?sectionHeader("","Tax Planning Recommendations")+recommendationList(r.recommendations.map(rec=>({priority:rec.priority,category:rec.category,text:rec.recommendation,saving:rec.estimatedSaving}))):""}
  ${pageFooter(2,10,inputs.meta.advisor.companyName)}</div>`;
}

function rrspSection(inputs: ComprehensiveReportInputs, r: RrspAnalysis): string {
  const rows = r.yearByYear.filter((_,i)=>i%3===0).slice(0,12).map(row=>[fmt.age(row.age),row.year.toString(),fmt.dollar(row.openingBalance),fmt.dollar(row.contribution),fmt.dollar(row.growth),fmt.dollar(row.closingBalance),fmt.dollar(row.taxRefund)]);
  return `<div class="page">${pageHeader(inputs.meta,"RRSP Analysis")}${sectionHeader("Section 3","RRSP Room & Optimization",`Tax Year ${new Date().getFullYear()}`)}
  ${metricGrid([{label:"Available Room",value:fmt.dollar(r.totalAvailableRoom),variant:"navy"},{label:"New Room This Year",value:fmt.dollar(r.newRoomThisYear)},{label:"Tax Refund @ Marginal",value:fmt.dollar(r.taxRefundAtMarginalRate),variant:"green"},{label:"Effective Cost",value:fmt.dollar(r.effectiveCostAfterRefund),sub:"After tax refund"}])}
  ${metricGrid([{label:"Projected at Retirement",value:fmt.dollar(r.projectedBalanceAtRetirement),variant:"blue"},{label:"Annual Withdrawal (4%)",value:fmt.dollar(r.projectedAnnualWithdrawal)},{label:"Years of Growth",value:r.yearsOfGrowth.toString()},{label:"Maximize Room by",value:`Age ${r.maximizeByAge}`}])}
  ${callout(r.catchUpStrategy,r.currentRoom>r.projectedAnnualWithdrawal?"warning":"success")}
  ${lineChart("RRSP Balance Projection",[{label:"RRSP Balance",data:r.yearByYear.map(row=>({x:row.age,y:row.closingBalance})),color:"#1E5FA8"},{label:"Cumulative Contributions",data:r.yearByYear.map(row=>({x:row.age,y:row.cumulativeContributions})),color:"#C9A84C"}])}
  ${dataTable("RRSP Growth Projection",[{label:"Age"},{label:"Year"},{label:"Opening Balance",right:true},{label:"Contribution",right:true},{label:"Growth",right:true},{label:"Closing Balance",right:true},{label:"Tax Refund",right:true}],rows)}
  ${callout(`<strong>Home Buyers Plan (HBP):</strong> First-time homebuyers may withdraw up to ${fmt.dollar(r.homeByersAmount)} from their RRSP tax-free, repayable over 15 years. &nbsp;<strong>Lifelong Learning Plan (LLP):</strong> Up to ${fmt.dollar(r.lifelongLearningAmount)} for full-time education, repayable over 10 years.`,"info")}
  ${pageFooter(3,10,inputs.meta.advisor.companyName)}</div>`;
}

function tfsaSection(inputs: ComprehensiveReportInputs, r: TfsaAnalysis): string {
  const rows = r.yearByYear.filter((_,i)=>i%3===0).slice(0,12).map(row=>[fmt.age(row.age),row.year.toString(),fmt.dollar(row.annualLimit),fmt.dollar(row.cumulativeRoom),fmt.dollar(row.contribution),fmt.dollar(row.growth),fmt.dollar(row.closingBalance)]);
  return `<div class="page">${pageHeader(inputs.meta,"TFSA Analysis")}${sectionHeader("Section 4","TFSA Room & Strategy",`Lifetime room since ${Math.max(2009,(inputs.tfsa?.birthYear??1980)+18)}`)}
  ${metricGrid([{label:"Lifetime Room to Date",value:fmt.dollar(r.lifetimeRoomToDate),variant:"navy"},{label:"Available Room Now",value:fmt.dollar(r.currentAvailableRoom),variant:r.currentAvailableRoom>0?"green":"amber"},{label:"2024 Annual Limit",value:fmt.dollar(r.new2024Room)},{label:"Withdrawal Room Recovered",value:fmt.dollar(r.withdrawalRoomRecovered)}])}
  ${metricGrid([{label:"Balance in 10 Years",value:fmt.dollar(r.projectedBalance10Years),variant:"blue"},{label:"Balance in 20 Years",value:fmt.dollar(r.projectedBalance20Years),variant:"blue"},{label:"Balance at Retirement",value:fmt.dollar(r.projectedBalanceAtRetirement),variant:"blue"},{label:"Optimal Withdrawal Age",value:`Age ${r.optimalWithdrawalAge}`}])}
  ${lineChart("TFSA vs. Taxable Account \u2014 Tax-Free Advantage",[{label:"TFSA Balance",data:r.taxFreeSavingsVsTaxable.map(row=>({x:row.year,y:row.tfsaBalance})),color:"#1E5FA8"},{label:"Taxable Account",data:r.taxFreeSavingsVsTaxable.map(row=>({x:row.year,y:row.taxableBalance})),color:"#D4860A"},{label:"TFSA Advantage",data:r.taxFreeSavingsVsTaxable.map(row=>({x:row.year,y:row.tfsaAdvantage})),color:"#1A7A4A"}])}
  ${callout(r.withdrawalStrategy,"info")}
  ${dataTable("TFSA Annual Contribution Room & Growth",[{label:"Age"},{label:"Year"},{label:"Annual Limit",right:true},{label:"Cumulative Room",right:true},{label:"Contribution",right:true},{label:"Growth",right:true},{label:"Closing Balance",right:true}],rows)}
  ${pageFooter(4,10,inputs.meta.advisor.companyName)}</div>`;
}

function capitalGainsSection(inputs: ComprehensiveReportInputs, r: CapitalGainsAnalysis): string {
  return `<div class="page">${pageHeader(inputs.meta,"Capital Gains")}${sectionHeader("Section 5","Capital Gains Analysis","2024 \u2014 Dual Inclusion Rate Applies")}
  ${callout(`<strong>2024 Capital Gains Inclusion Rate Change:</strong> For individuals, the first $250,000 of net annual capital gains remains at a 50% inclusion rate. Gains above $250,000 are now included at 66.67% (effective June 25, 2024).`,"warning")}
  ${metricGrid([{label:"Total Proceeds",value:fmt.dollar(r.totalProceeds)},{label:"Total Adjusted Cost Base",value:fmt.dollar(r.totalACB)},{label:"Net Capital Gain",value:fmt.dollar(r.netGain),variant:r.netGain>0?"amber":"green"},{label:"Tax on Gains",value:fmt.dollar(r.totalTaxOnGains),variant:"red"}])}
  ${metricGrid([{label:"Gains at 50% Inclusion",value:fmt.dollar(r.gainUnder250k),sub:"Under $250,000 threshold"},{label:"Gains at 66.67% Inclusion",value:fmt.dollar(r.gainOver250k),sub:"Over $250,000 threshold",variant:r.gainOver250k>0?"amber":""},{label:"Taxable Gain",value:fmt.dollar(r.taxableGain)},{label:"Effective Rate on Gains",value:fmt.pct(r.effectiveRateOnGains)}])}
  ${r.disposalBreakdown.length>0?dataTable("Disposition Details",[{label:"Description"},{label:"Type"},{label:"Proceeds",right:true},{label:"ACB",right:true},{label:"Gain/Loss",right:true},{label:"Taxable Gain",right:true},{label:"Est. Tax",right:true}],r.disposalBreakdown.map(d=>[d.description,d.assetType.replace(/_/g," "),fmt.dollar(d.proceeds),fmt.dollar(d.acb),fmt.dollar(d.gain),fmt.dollar(d.taxableGain),fmt.dollar(d.estimatedTax)]),["TOTAL","",fmt.dollar(r.totalProceeds),fmt.dollar(r.totalACB),fmt.dollar(r.netGain),fmt.dollar(r.taxableGain),fmt.dollar(r.totalTaxOnGains)]):""}
  ${r.lcgeUsed>0||r.lcgeRemaining>0?metricGrid([{label:"Lifetime Capital Gains Exemption",value:fmt.dollar(r.lifetimeCapitalGainsExemption),sub:"2024 QSBC limit"},{label:"LCGE Used",value:fmt.dollar(r.lcgeUsed),variant:r.lcgeUsed>0?"amber":""},{label:"LCGE Remaining",value:fmt.dollar(r.lcgeRemaining),variant:"green"}],3):""}
  ${r.timingRecommendations.length>0?recommendationList(r.timingRecommendations.map(t=>({priority:"medium",category:"Timing Strategy",text:t}))):""}
  ${r.harvestingOpportunities.length>0?recommendationList(r.harvestingOpportunities.map(t=>({priority:"high",category:"Tax-Loss Harvesting",text:t}))):""}
  ${pageFooter(5,10,inputs.meta.advisor.companyName)}</div>`;
}

function incomeSplittingSection(inputs: ComprehensiveReportInputs, r: IncomeSplittingAnalysis): string {
  return `<div class="page">${pageHeader(inputs.meta,"Income Splitting")}${sectionHeader("Section 6","Income Splitting Strategies","T1032 Pension Splitting & Spousal RRSP")}
  ${metricGrid([{label:"Current Combined Tax",value:fmt.dollar(r.currentCombinedTax),variant:"red"},{label:"After Splitting Tax",value:fmt.dollar(r.combinedAfterSplitTax),variant:"green"},{label:"Annual Tax Saving",value:fmt.dollar(r.totalAnnualSaving),variant:"green"},{label:"Lifetime Tax Saving",value:fmt.dollar(r.totalLifetimeSaving),variant:"navy"}])}
  ${dataTable("Before vs. After Income Splitting",[{label:"Taxpayer"},{label:"Before: Tax",right:true},{label:"Before: Eff. Rate",right:true},{label:"After: Tax",right:true},{label:"After: Eff. Rate",right:true},{label:"Saving",right:true}],[[inputs.meta.client.fullName+" (Primary)",fmt.dollar(r.primaryCurrentTax),fmt.pct(r.comparison.beforeSplitting.effectivePrimary/100),fmt.dollar(r.primaryAfterSplitTax),fmt.pct(r.comparison.afterSplitting.effectivePrimary/100),fmt.dollar(r.primaryCurrentTax-r.primaryAfterSplitTax)],[(inputs.meta.client.spouseFirstName??"Spouse")+" (Spouse)",fmt.dollar(r.spouseCurrentTax),fmt.pct(r.comparison.beforeSplitting.effectiveSpouse/100),fmt.dollar(r.spouseAfterSplitTax),fmt.pct(r.comparison.afterSplitting.effectiveSpouse/100),fmt.dollar(r.spouseCurrentTax-r.spouseAfterSplitTax)]],["Combined",fmt.dollar(r.currentCombinedTax),"—",fmt.dollar(r.combinedAfterSplitTax),"—",fmt.dollar(r.pensionSplitTaxSaving)])}
  ${sectionHeader("","Available Strategies")}
  ${r.strategies.map(s=>`<div class="rec-item ${s.eligible?(s.annualSaving>5000?"high":"medium"):"low"}" style="margin-bottom:10px"><div class="rec-icon">${s.eligible?"&#9873;":"&#8211;"}</div><div class="rec-body"><div class="rec-category">${s.name} ${s.eligible?badge("ELIGIBLE","green"):badge("NOT ELIGIBLE","red")}</div><div class="rec-text">${s.description}</div>${s.eligible&&s.annualSaving>0?`<div class="rec-saving">Annual saving: ${fmt.dollar(s.annualSaving)} &mdash; ${s.actionRequired}</div>`:`<div class="text-xs mt-4">${s.actionRequired}</div>`}</div></div>`).join("")}
  ${r.spousalRrspRecommended?callout(r.spousalRrspRationale,"info"):""}
  ${pageFooter(6,10,inputs.meta.advisor.companyName)}</div>`;
}

function insuranceSection(inputs: ComprehensiveReportInputs, r: InsuranceAnalysis): string {
  return `<div class="page">${pageHeader(inputs.meta,"Insurance Needs Analysis")}${sectionHeader("Section 7","Insurance Needs Analysis","Life, Disability & Critical Illness")}
  ${metricGrid([{label:"Life Insurance Gap",value:fmt.dollar(r.dimeGap),variant:r.dimeGap>0?"red":"green"},{label:"Recommended Coverage",value:fmt.dollar(r.recommendedLifeCoverage),variant:"navy"},{label:"Disability Gap (Monthly)",value:fmt.dollar(r.disabilityGap)+"/mo",variant:r.disabilityGap>0?"amber":"green"},{label:"Critical Illness Gap",value:fmt.dollar(r.ciGap),variant:r.ciGap>0?"amber":"green"}])}
  ${dataTable("Life Insurance Needs \u2014 DIME Method",[{label:"Component"},{label:"Amount",right:true},{label:"Notes"}],[["Debt (D)",fmt.dollar(r.dimeDebt),"Total liabilities + final expenses"],["Income Replacement (I)",fmt.dollar(r.dimeIncome),`${Math.round(r.dimeIncome/(inputs.insurance?.annualIncome||1))} years income replacement`],["Mortgage (M)",fmt.dollar(r.dimeMortgage),"Outstanding mortgage balance"],["Education (E)",fmt.dollar(r.dimeEducation),"Children's education costs"],["Total DIME Need",fmt.dollar(r.dimeTotalNeed),""],["Less: Existing Coverage",`(${fmt.dollar(r.dimeExistingCoverage)})`,"Life insurance + liquid assets"]],["Coverage Gap",fmt.dollar(r.dimeGap),`${r.recommendedCoverageType.replace(/_/g," ")} recommended`])}
  <div class="two-col mb-20"><div>${metricGrid([{label:"Human Life Value",value:fmt.dollar(r.hlvValue),sub:"Income capitalization"},{label:"HLV Gap",value:fmt.dollar(r.hlvGap),variant:r.hlvGap>0?"amber":"green"}],2)}</div><div>${metricGrid([{label:"Needs-Based Requirement",value:fmt.dollar(r.needsBasedCapitalNeeded)},{label:"Needs-Based Gap",value:fmt.dollar(r.needsBasedGap),variant:r.needsBasedGap>0?"amber":"green"}],2)}</div></div>
  ${dataTable("Disability & Critical Illness",[{label:"Coverage Type"},{label:"Monthly Need",right:true},{label:"Existing",right:true},{label:"Gap",right:true},{label:"Est. Premium",right:true}],[["Long-term Disability",fmt.dollar(r.monthlyDisabilityNeed)+"/mo",fmt.dollar(r.existingDisabilityCoverage)+"/mo",fmt.dollar(r.disabilityGap)+"/mo",fmt.dollar(r.estimatedDisabilityPremium)+"/mo"],["Critical Illness (Lump Sum)",fmt.dollar(r.recommendedCICoverage),fmt.dollar(inputs.insurance?.existingCriticalIllness??0),fmt.dollar(r.ciGap),fmt.dollar(r.estimatedCIPremium)+"/mo"]])}
  ${recommendationList(r.recommendations.map(rec=>({priority:rec.priority,category:rec.type.replace(/_/g," ").replace(/\b\w/g,(l:string)=>l.toUpperCase()),text:rec.rationale})))}
  ${pageFooter(7,10,inputs.meta.advisor.companyName)}</div>`;
}

function educationSection(inputs: ComprehensiveReportInputs, r: EducationAnalysis): string {
  return `<div class="page">${pageHeader(inputs.meta,"Education Planning (RESP)")}${sectionHeader("Section 8","Education Planning \u2014 RESP","Canada Education Savings Grant & Canada Learning Bond")}
  ${metricGrid([{label:"Total Projected RESP",value:fmt.dollar(r.totalProjectedRespValue),variant:"navy"},{label:"Total CESG Received",value:fmt.dollar(r.totalCesgReceived),variant:"green"},{label:"Estimated Education Cost",value:fmt.dollar(r.totalEstimatedEducationCost)},{label:"Surplus / (Shortfall)",value:fmt.dollar(r.shortfallOrSurplus),variant:r.shortfallOrSurplus>=0?"green":"red"}])}
  ${callout(`<strong>CESG Rate:</strong> ${fmt.pct(r.familyCesgRate)} on the first $2,500 contributed per child per year (max $500/year, $7,200 lifetime).${r.additionalCesgPerChild>0?` <strong>Additional CESG:</strong> Your family income qualifies for an additional $${r.additionalCesgPerChild}/year per child.`:""}${r.clbPerChild>0?` <strong>Canada Learning Bond:</strong> Your family may qualify for ${fmt.dollar(r.clbPerChild)} per child.`:""}`,r.familyCesgRate>0.20?"success":"info")}
  ${r.children.map(child=>`<div class="no-break"><div class="table-title" style="padding:12px 0 8px;font-size:14px;color:var(--navy);font-weight:600;">${child.name} \u2014 Age ${child.age} (${child.yearsUntilPostSecondary} years until post-secondary)</div>${metricGrid([{label:"Projected RESP Balance",value:fmt.dollar(child.projectedRespBalance),variant:"blue"},{label:"Total CESG",value:fmt.dollar(child.totalCesgForChild),variant:"green"},{label:"Estimated Program Cost",value:fmt.dollar(child.estimatedEducationCost)},{label:"Surplus / (Shortfall)",value:fmt.dollar(child.shortfallOrSurplus),variant:child.shortfallOrSurplus>=0?"green":"red"}])}${dataTable("",[{label:"Year"},{label:"Child Age"},{label:"Contribution",right:true},{label:"CESG",right:true},{label:"Add'l CESG",right:true},{label:"Growth",right:true},{label:"Balance",right:true}],child.yearByYear.filter((_,i)=>i%2===0).map(row=>[row.year.toString(),row.childAge.toString(),fmt.dollar(row.contribution),fmt.dollar(row.cesg),fmt.dollar(row.additionalCesg),fmt.dollar(row.growth),fmt.dollar(row.closingBalance)]))}</div>`).join(divider())}
  ${pageFooter(8,10,inputs.meta.advisor.companyName)}</div>`;
}

function estateSection(inputs: ComprehensiveReportInputs, r: EstateAnalysis): string {
  const docItems = Object.entries(r.documentStatus).map(([key,val])=>({name:key.replace(/([A-Z])/g," $1").replace(/\b\w/g,(l:string)=>l.toUpperCase()),has:(val as any).hasDocument,rec:(val as any).recommendation}));
  return `<div class="page">${pageHeader(inputs.meta,"Estate Planning")}${sectionHeader("Section 9","Estate Planning",`Province: ${PROVINCE_NAMES[inputs.estate?.province??inputs.meta.client.province]}`)}
  ${metricGrid([{label:"Gross Estate",value:fmt.dollar(r.grossEstate)},{label:"Net Estate",value:fmt.dollar(r.netEstate),variant:"navy"},{label:"Estimated Tax on Death",value:fmt.dollar(r.totalTaxOnDeath),variant:"red"},{label:"Estate After Tax & Probate",value:fmt.dollar(r.estateAfterTaxAndProbate),variant:"green"}])}
  ${metricGrid([{label:"Probate Fees",value:fmt.dollar(r.probateFees),variant:r.probateFees>10000?"amber":""},{label:"Assets Bypassing Probate",value:fmt.dollar(r.assetsBypassingProbate),variant:"green"},{label:"RRSP/RRIF Tax on Death",value:fmt.dollar(r.taxOnRrsp),variant:r.taxOnRrsp>0?"red":""},{label:"Capital Gains Tax on Death",value:fmt.dollar(r.taxOnCapitalGains),variant:r.taxOnCapitalGains>0?"amber":""}])}
  ${barChart("Estate Distribution Overview",[{label:"To Spouse",value:r.toSpouse,color:"#1A7A4A"},{label:"Estate (Net)",value:r.estateAfterTaxAndProbate,color:"#1E5FA8"},{label:"Tax on Death",value:r.totalTaxOnDeath,color:"#C0392B"},{label:"Probate Fees",value:r.probateFees,color:"#D4860A"}])}
  <div class="table-title mb-12">Document Status Checklist</div>
  <div class="rec-list">${docItems.map(d=>`<div class="rec-item ${d.has?"low":"immediate"}"><div class="rec-icon">${d.has?"&#9745;":"&#9888;"}</div><div class="rec-body"><div class="rec-category">${d.name} ${d.has?badge("IN PLACE","green"):badge("MISSING","red")}</div><div class="rec-text">${d.rec}</div></div></div>`).join("")}</div>
  ${r.recommendations.length>0?recommendationList(r.recommendations.map(rec=>({priority:rec.priority,category:rec.category,text:rec.recommendation,saving:rec.estimatedSaving}))):""}
  ${callout(`<strong>Estate Liquidity Needed:</strong> ${fmt.dollar(r.estimatedLiquidityNeeded)} required to cover taxes and probate fees on death.${r.lifeInsuranceSuggested>0?` A life insurance policy of ${fmt.dollar(r.lifeInsuranceSuggested)} is recommended to provide tax-free liquidity.`:" Current assets provide sufficient liquidity."}`,r.lifeInsuranceSuggested>0?"warning":"success")}
  ${pageFooter(9,10,inputs.meta.advisor.companyName)}</div>`;
}

function debtSection(inputs: ComprehensiveReportInputs, r: DebtAnalysis): string {
  return `<div class="page">${pageHeader(inputs.meta,"Debt & Cash Flow")}${sectionHeader("Section 10","Debt & Cash Flow Analysis","Debt Payoff Strategy & Monthly Budget")}
  ${metricGrid([{label:"Total Debt",value:fmt.dollar(r.totalDebt),variant:r.totalDebt>0?"amber":"green"},{label:"Monthly Surplus/Deficit",value:fmt.dollar(r.monthlySurplusOrDeficit),variant:r.monthlySurplusOrDeficit>=0?"green":"red"},{label:"Savings Rate",value:fmt.pct(r.savingsRate),variant:r.savingsRate>=0.15?"green":"amber"},{label:"Debt-Free Date",value:r.debtFreeDate,variant:"navy"}])}
  <div class="two-col mb-20"><div>
  <div class="table-title mb-8">Debt Service Ratios</div>
  ${progressBar("GDSR (max 32%)",r.grossDebtServiceRatio,0.44,r.grossDebtServiceRatio>0.32?"red":"green")}
  ${progressBar("TDSR (max 44%)",r.totalDebtServiceRatio,0.44,r.totalDebtServiceRatio>0.44?"red":r.totalDebtServiceRatio>0.36?"amber":"green")}
  ${metricGrid([{label:"GDSR",value:fmt.pct(r.grossDebtServiceRatio),variant:r.grossDebtServiceRatio>0.32?"red":"green",sub:"Max 32% recommended"},{label:"TDSR",value:fmt.pct(r.totalDebtServiceRatio),variant:r.totalDebtServiceRatio>0.44?"red":r.totalDebtServiceRatio>0.36?"amber":"green",sub:"Max 44% (lender limit)"}],2)}
  </div><div>${metricGrid([{label:"Emergency Fund",value:`${r.emergencyFundMonthsCovered.toFixed(1)} months`,variant:r.emergencyFundStatus==="adequate"?"green":r.emergencyFundStatus==="building"?"amber":"red"},{label:"Status",value:r.emergencyFundStatus.toUpperCase(),sub:r.emergencyFundStatus==="adequate"?"3-6 months covered":"Below 3-month target"}],2)}</div></div>
  ${dataTable("Monthly Cash Flow Budget",[{label:"Category"},{label:"Monthly Amount",right:true},{label:"Annual",right:true},{label:"% of Net Income",right:true}],[["Gross Income",fmt.dollar(r.monthlyBudget.grossIncome),fmt.dollar(r.monthlyBudget.grossIncome*12),"100%"],["Less: Taxes",`(${fmt.dollar(r.monthlyBudget.taxes)})`,`(${fmt.dollar(r.monthlyBudget.taxes*12)})`,""],[`Net Income`,fmt.dollar(r.monthlyBudget.netIncome),fmt.dollar(r.monthlyBudget.netIncome*12),"100%"],["Housing",fmt.dollar(r.monthlyBudget.housing),fmt.dollar(r.monthlyBudget.housing*12),fmt.pct(r.monthlyBudget.housing/Math.max(r.monthlyBudget.netIncome,1))],["Transportation",fmt.dollar(r.monthlyBudget.transportation),fmt.dollar(r.monthlyBudget.transportation*12),fmt.pct(r.monthlyBudget.transportation/Math.max(r.monthlyBudget.netIncome,1))],["Food",fmt.dollar(r.monthlyBudget.food),fmt.dollar(r.monthlyBudget.food*12),fmt.pct(r.monthlyBudget.food/Math.max(r.monthlyBudget.netIncome,1))],["Debt Payments",fmt.dollar(r.monthlyBudget.debtPayments),fmt.dollar(r.monthlyBudget.debtPayments*12),fmt.pct(r.monthlyBudget.debtPayments/Math.max(r.monthlyBudget.netIncome,1))],["Savings",fmt.dollar(r.monthlyBudget.savings),fmt.dollar(r.monthlyBudget.savings*12),fmt.pct(r.monthlyBudget.savings/Math.max(r.monthlyBudget.netIncome,1))],["Discretionary",fmt.dollar(r.monthlyBudget.discretionary),fmt.dollar(r.monthlyBudget.discretionary*12),fmt.pct(r.monthlyBudget.discretionary/Math.max(r.monthlyBudget.netIncome,1))]],["Monthly Surplus",fmt.dollar(r.monthlyBudget.surplus),fmt.dollar(r.monthlyBudget.surplus*12),fmt.pct(r.monthlyBudget.surplus/Math.max(r.monthlyBudget.netIncome,1))])}
  ${dataTable(`Debt Payoff \u2014 Avalanche Method (Saves ${fmt.dollar(r.avalancheInterestSaved)} vs Snowball)`,[{label:"Priority"},{label:"Debt"},{label:"Balance",right:true},{label:"Rate",right:true},{label:"Min Payment",right:true},{label:"Payoff Date"},{label:"Total Interest",right:true}],r.avalancheOrder.map(d=>[`#${d.payoffOrder}`,d.name,fmt.dollar(d.balance),fmt.pct(d.interestRate),fmt.dollar(d.minimumPayment),d.payoffDate,fmt.dollar(d.totalInterestPaid)]))}
  ${r.recommendations.length>0?recommendationList(r.recommendations.map(rec=>({priority:rec.priority,category:rec.category,text:rec.recommendation,saving:rec.monthlyImpact*12}))):""}
  ${pageFooter(10,10,inputs.meta.advisor.companyName)}</div>`;
}

export function generateComprehensiveReport(
  inputs: ComprehensiveReportInputs,
  results: { retirement?: RetirementProjection; tax?: TaxProjection; rrsp?: RrspAnalysis; tfsa?: TfsaAnalysis; capitalGains?: CapitalGainsAnalysis; incomeSplitting?: IncomeSplittingAnalysis; insurance?: InsuranceAnalysis; education?: EducationAnalysis; estate?: EstateAnalysis; debt?: DebtAnalysis; }
): string {
  const tocItems: string[] = [], sections: string[] = [];
  if (results.retirement)     { tocItems.push("Retirement Planning (RRSP/RRIF/CPP/OAS)"); sections.push(retirementSection(inputs, results.retirement)); }
  if (results.tax)            { tocItems.push("Tax Projection & Planning"); sections.push(taxSection(inputs, results.tax)); }
  if (results.rrsp)           { tocItems.push("RRSP Room & Optimization"); sections.push(rrspSection(inputs, results.rrsp)); }
  if (results.tfsa)           { tocItems.push("TFSA Room & Strategy"); sections.push(tfsaSection(inputs, results.tfsa)); }
  if (results.capitalGains)   { tocItems.push("Capital Gains Analysis"); sections.push(capitalGainsSection(inputs, results.capitalGains)); }
  if (results.incomeSplitting){ tocItems.push("Income Splitting (T1032)"); sections.push(incomeSplittingSection(inputs, results.incomeSplitting)); }
  if (results.insurance)      { tocItems.push("Insurance Needs Analysis"); sections.push(insuranceSection(inputs, results.insurance)); }
  if (results.education)      { tocItems.push("Education Planning (RESP)"); sections.push(educationSection(inputs, results.education)); }
  if (results.estate)         { tocItems.push("Estate Planning"); sections.push(estateSection(inputs, results.estate)); }
  if (results.debt)           { tocItems.push("Debt & Cash Flow"); sections.push(debtSection(inputs, results.debt)); }
  return `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<title>${inputs.meta.reportTitle} \u2014 ${inputs.meta.client.fullName}</title>\n<style>${REPORT_CSS}</style>\n</head>\n<body>\n${coverPage(inputs.meta, tocItems)}\n${sections.join("\n")}\n</body>\n</html>`;
}
